# Generated by Django 4.0.4 on 2022-05-16 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.CharField(choices=[('B', 'Im before work'), ('A', 'Im after work')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 19, 49, 12, 280992, tzinfo=utc)),
        ),
    ]
