# Generated by Django 4.0.4 on 2022-05-16 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_state_alter_game_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 16, 19, 49, 57, 949254, tzinfo=utc)),
        ),
    ]
