# Generated by Django 4.0.4 on 2022-05-21 19:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_start_time_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 19, 5, 34, 24422, tzinfo=utc)),
        ),
    ]
