# Generated by Django 4.0.4 on 2022-05-22 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='avg_speed',
            field=models.DecimalField(decimal_places=3, default=10.12, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 19, 35, 59, 14352, tzinfo=utc)),
        ),
    ]
